version: '3'
services:
  db:
    image: postgres
  redis:
    image: redis
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/scorebot
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
    depends_on:
      - db
      - redis
  httpd:
    build: ../scorebot-httpd
    volumes:
      - ../scorebot-httpd:/scorebot-httpd
      - .:/scorebot
    ports:
      - "443:443"
    depends_on:
      - web
  service:
    build: .
    command: bundle exec ruby bin/service
    volumes:
      - .:/scorebot
    environment:
      - RAILS_ENV=production
    depends_on:
      - db
      - redis
