version: '3'
services:
  db:
    image: postgres
    command: postgres -c max_connections=500 -c shared_buffers=512MB
    ports:
      - "5432:5432"
  dump:
    image: postgres
    command: bash
    volumes:
      - .:/scorebot
    depends_on:
      - db
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/scorebot
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
    depends_on:
      - db
      - redis
  httpd:
    build: ../scorebot-httpd
    volumes:
      - ../scorebot-httpd:/scorebot-httpd
      - .:/scorebot
    ports:
      - "443:443"
    depends_on:
      - web
  service:
    build: .
    command: bundle exec bash
    volumes:
      - .:/scorebot
    environment:
      - RAILS_ENV=production
    depends_on:
      - db
      - redis
